GestionAchatErp/Models/ExpressionBesoin.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GestionAchatErp.Models
{
    public class ExpressionBesoin
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public int UserIdResponsable { get; set; }
        public int DirectionId { get; set; }
        public int DepartementId { get; set; }
        public int FonctionId { get; set; }
        public int SourceBudgetaire { get; set; }
        public int CrbEnCharge { get; set; }

        [Display(Name = "Nom du demandeur")]
        public string NomDemandeur { get; set; }
        [Display(Name = "Direction")]
        public string DirectionLibelle { get; set; }
        [Display(Name = "Département")]
        public string DepartementLibelle { get; set; }
        public string Fonction { get; set; }
        [Display(Name = "Numéro du besoin")]
        public string NumExpressionBesoin { get; set; }
        [Display(Name = "Nature du besoin")]
        public string NatureBesoin { get; set; }
        [Display(Name = "Motif de la demande")]
        public string MotifDemande { get; set; }
        [Display(Name = "Date de la demande")]
        public DateTime DateDemande { get; set; }
        [Display(Name = "Statut de la demande")]
        public string DernierStatut { get; set; }
        [Display(Name = "Date Statut")]
        public DateTime DateStatut { get; set; }
        public string Observation { get; set; }
        public string Commentaire { get; set; }
        public virtual UserProfile UserProfile { get; set; }


    }
}

GestionAchatErp/Controllers/ExpressionBesoinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionAchatErp.Data;
using GestionAchatErp.Models;
using static GestionAchatErp.Pages.MainMenu;
using SendGrid;
using Microsoft.AspNetCore.Identity;
using GestionAchatErp.Helpers;
using GestionAchatErp.Services;

namespace GestionAchatErp.Controllers
{
    public class ExpressionBesoinsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly INumberSequence _numberSequence;

        public ExpressionBesoinsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            INumberSequence numberSequence)
        {
            _context = context;
            _userManager = userManager;
            _numberSequence = numberSequence;
        } 



        // GET: ExpressionBesoins
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ExpressionBesoin.Include(e => e.UserProfile);
            return View(await applicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> SuivreMesBesoins()
        {
            var applicationDbContext = _context.ExpressionBesoin.Include(e => e.UserProfile);
            return View("SuivreMesBesoins", await applicationDbContext.ToListAsync()); ;

        }

        
        [HttpPost]
        public async Task<JsonResult> GetMesExpressionBesoins()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var data = _context.Set<ExpressionBesoin>().AsQueryable();
            ApplicationUser user = await _userManager.GetUserAsync(User);
            UserProfile userProfile = _context.UserProfile.SingleOrDefault(x => x.ApplicationUserId.Equals(user.Id));
            //get total count of data in table
            totalRecord = data.Count();
            // search data when search value found
            data = data.Where(x => x.UserProfileId.Equals(userProfile.UserProfileId) && x.DirectionId.Equals(userProfile.DirectionId) && x.DepartementId.Equals(userProfile.DepartementId)).OrderByDescending(x=> x.Id) ;
            if (!string.IsNullOrEmpty(searchValue))
            {
                data = data.Where(x => x.NomDemandeur.ToLower().Contains(searchValue.ToLower()) || x.DirectionLibelle.ToLower().Contains(searchValue.ToLower()) || x.DepartementLibelle.ToLower().Contains(searchValue.ToLower()));
            }
            // get total count of records after search
            filterRecord = data.Count();
            //sort data
            //if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection)) data = data.OrderBy(sortColumn + " " + sortColumnDirection);
            //pagination
            var empList = data.Skip(skip).Take(pageSize).ToList();
            var returnObj = new
            {
                draw = draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = empList
            };

            return Json(returnObj);
        }
        // GET: ExpressionBesoins à valider
        public async Task<IActionResult> ListeValider()
        {
            var applicationDbContext = _context.ExpressionBesoin.Include(e => e.UserProfile);
            return View("ListeAValider",await applicationDbContext.ToListAsync());;
        }


        public async Task<IActionResult> ListeValiderCrb()
        {
            var applicationDbContext = _context.ExpressionBesoin.Include(e => e.UserProfile);
            return View("ListeAValiderCrb", await applicationDbContext.ToListAsync()); ;

        }

        public async Task<IActionResult> ListeValiderRCrb()
        {
            var applicationDbContext = _context.ExpressionBesoin.Include(e => e.UserProfile);
            return View("ListeAValiderRespCrb", await applicationDbContext.ToListAsync()); ;
        }

        [HttpPost]
        public async Task<JsonResult> GetExpressionBesoinsList()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var data = _context.Set<ExpressionBesoin>().AsQueryable();
            ApplicationUser user = await _userManager.GetUserAsync(User);
            UserProfile userProfile = _context.UserProfile.SingleOrDefault(x => x.ApplicationUserId.Equals(user.Id));
            //get total count of data in table
            totalRecord = data.Count();
            // search data when search value found
            data = data.Where(x => x.UserProfileId.Equals(userProfile.UserProfileId) && x.DirectionId.Equals(userProfile.DirectionId) && x.DepartementId.Equals(userProfile.DepartementId) && x.DernierStatut == "CREER");
            if (!string.IsNullOrEmpty(searchValue))
            {
                data = data.Where(x => x.NomDemandeur.ToLower().Contains(searchValue.ToLower()) || x.DirectionLibelle.ToLower().Contains(searchValue.ToLower()) || x.DepartementLibelle.ToLower().Contains(searchValue.ToLower()));
            }
            // get total count of records after search
            filterRecord = data.Count();
            //sort data
            //if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection)) data = data.OrderBy(sortColumn + " " + sortColumnDirection);
            //pagination
            var empList = data.Skip(skip).Take(pageSize).ToList();
            var returnObj = new
            {
                draw = draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = empList
            };

            return  Json(returnObj);
        }
        [HttpPost]
        public async Task<JsonResult> GetExpressionBesoinsListValider()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var data = _context.Set<ExpressionBesoin>().AsQueryable();
            ApplicationUser user = await _userManager.GetUserAsync(User);
            UserProfile userProfile = _context.UserProfile.SingleOrDefault(x => x.ApplicationUserId.Equals(user.Id));
            //get total count of data in table
            totalRecord = data.Count();
            // search data when search value found
            
            data = data.Where(x =>  x.DirectionId.Equals(userProfile.DirectionId) && x.DepartementId.Equals(userProfile.DepartementId) && x.DernierStatut.ToLower().Contains("SOUMETTRE"));
            if (!string.IsNullOrEmpty(searchValue))
            {
                data = data.Where(x => x.NomDemandeur.ToLower().Contains(searchValue.ToLower()) || x.DirectionLibelle.ToLower().Contains(searchValue.ToLower()) || x.DepartementLibelle.ToLower().Contains(searchValue.ToLower()));
            }
            data= data.OrderBy(x => x.DernierStatut);
            // get total count of records after search
            filterRecord = data.Count();
            //sort data
            //if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection)) data = data.OrderBy(sortColumn + " " + sortColumnDirection);
            //pagination
            var empList = data.Skip(skip).Take(pageSize).ToList();
            var returnObj = new
            {
                draw = draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = empList
            };

            return Json(returnObj);
        }


        [HttpPost]
        public async Task<JsonResult> GetExpressionBesoinsListValiderCrb()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");

GestionAchatErp/Views/ExpressionBesoins/Create.cshtml
@model GestionAchatErp.Models.ExpressionBesoin

    <div class="modal-header">
    <h4 class="modal-title">Ajout: Expression Besoin</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>

    <div class="modal-body">
    <form id="myForm" >
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.AntiForgeryToken()
        <div class="row">
            
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="NatureBesoin" class="control-label"></label>
                    <input asp-for="NatureBesoin" class="form-control" />
                    <span asp-validation-for="NatureBesoin" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="MotifDemande" class="control-label"></label>
                    <input asp-for="MotifDemande" class="form-control" />
                    <span asp-validation-for="MotifDemande" class="text-danger"></span>
                </div>
            </div>
        </div>
       
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            <button type="button" id="SaveData" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
    </div>
   

GestionAchatErp/Views/ExpressionBesoins/Index.cshtml
@model IEnumerable<GestionAchatErp.Models.ExpressionBesoin>
@{
    ViewBag.Title = "Liste des Expressions de Besoins";
}
<div class="container-fluid">

 <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> <a class="btn btn-primary" id="addButton"> <i class="fas fa-plus"></i> Ajouter</a></h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
    <table id="tableName" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Numéro</th>
                <th>Besoin</th>
                <th>Motif</th>
                <th>Demandeur</th>
                <th>@Html.DisplayNameFor(model => model.DirectionLibelle)</th>
                <th>@Html.DisplayNameFor(model => model.DepartementLibelle)</th>
                <th>Statut</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
           </thead>
                 
        </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</div>


@section Scripts{
    <!-- Page specific script -->
    <script>
        $(function () {
           var table = $("#tableName").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                processing: true,
                serverSide: true,
                filter: true,
                ajax: {
                   // url: "ExpressionBesoins/GetExpressionBesoinsList",
                    url: "@Url.Action("GetExpressionBesoinsList", "ExpressionBesoins")",
                    type: "POST",
                },
                columns: [
                    { data: "Id", name: "Id" },
                    { data: "NumExpressionBesoin", name: "NumExpressionBesoin" },
                    { data: "NatureBesoin", name: "NatureBesoin" },
                    { data: "MotifDemande", name: "MotifDemande" },
                    { data: "NomDemandeur", name: "NomDemandeur" },
                    { data: "DirectionLibelle", name: "DirectionLibelle" },
                    { data: "DepartementLibelle", name: "DepartementLibelle" },
                    {
                        data: "DernierStatut", render: function (data, type, row, meta) {
                            if (data=='CREER') {
                                return type === 'display' ?'<span class="badge badge-info" >' + data + '</span>' : data;
                            }
                            if (data == 'SOUMETTRE') {
                                return type === 'display' ? '<span class="badge badge-primary" >' + data + '</span>' : data;
                            }
                            if (data == 'REJETER') {
                                return type === 'display' ? '<span class="badge badge-danger" >' + data + '</span>' : data;
                            }
                            else{
                                return type === 'display' ? '<span class="badge badge-success" >' + data + '</span>' : data;
                            }
                            
                        }
                    },
                    { data: "DateDemande", name: "DateDemande" },
                    {
                        data: "Id", render: function (data, type, row, meta) {
                          /*  return type === 'display' ?
                                '<a href="/ItemsExpressionBesoins/List/' + data + '" ><i class="fas fa-plus"></i></a>' :
                                data;*/
                            var action = '<div>';
                            if (type === 'display') {
                                action += '<a href="/ItemsExpressionBesoins/List/' + data + '" ><i class="fas fa-plus"></i></a>  ';
                                if (row.DernierStatut == "CREER"){
                                     action += ' <a id="editButton" data-eb='+data+' href="#" ><i class="fas fa-edit"></i></a> ';
                                }
                               
                               
                            }
                            action += '</div>';
                            console.log("OK--> "+row.DernierStatut);
                            return action;
                        }
                    }
                ]
            });



            $("#addButton").click(function () {
                //var customerId = $(this).closest("tr").find("td").eq(0).html();
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Create", "ExpressionBesoins")",
                    //data: { "customerId": customerId },
                    success: function (response) {
                        $("#partialModal").find(".modal-content").html(response);
                        $("#partialModal").modal('show');
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            });


            $(document).on('click', '#SaveData', function (e) {
                e.preventDefault();
                var form = $(this).parents('form:first');
                var formData = form.serialize();
                $.ajax(
                    {
                        type: 'post',
                        url: "@Url.Action("Create", "ExpressionBesoins")",
                        data: formData,
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (result) {
                            //table.draw();
                            table.ajax.reload();
                            $('#partialModal').modal('hide');
                            var url = '@Url.Action("List", "ItemsExpressionBesoins")/'+ result;
                            console.log(url);
                            window.location.href = url;
                        }
                    });
            });



            //Edit script
            //Modifier une expression besion editButton
            $(document).on('click', '#editButton', function (e) {
                e.preventDefault();
                var id = $(this).data('eb');
                var url = "@Url.Action("ModifierExpressionBesoin", "ExpressionBesoins")/" + id;
                console.log('TEST OK'+id);
                //var customerId = $(this).closest("tr").find("td").eq(0).html();
                $.ajax({
                    type: "GET",
                    url: url,
                    //data: { "customerId": customerId },
                    success: function (response) {
                        $("#partialModal").find(".modal-content").html(response);
                        $("#partialModal").modal('show');
                        $('.modal-dialog').css('max-width', '50%');
                        //$('#myFormSoumettre input').prop('readonly', true);
                        //$('#myFormSoumettre textarea').prop('readonly', true);
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            });

            $(document).on('click', '#ModifierData', function (e) {
                e.preventDefault();
                var id = $(this).data('eb');
                var url = "@Url.Action("ModifierExpressionBesoin", "ExpressionBesoins")";
                console.log('TEST OK' + url);
                var form = $(this).parents('form:first');
                var formData = form.serialize();
                $.ajax(
                    {
                        type: 'post',
                        url: url,
                        data: formData,
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (result) {
                            //table.draw();
                            console.log(result);
                            table.ajax.reload();
                            $('#partialModal').modal('hide');
                        }
                    });
            });

            //Detail script

            //Delete script

              
        });
    </script>

}

GestionAchatErp/Views/ExpressionBesoins/ListeAValider.cshtml
@model IEnumerable<GestionAchatErp.Models.ExpressionBesoin>
@{
    ViewBag.Title = "Liste des Expressions de Besoins";
}
<div class="container-fluid">

 <!-- /.card -->

    <div class="card">
        <!--  <div class="card-header">
            <h3 class="card-title"> <a class="btn btn-primary" id="addButton"> <i class="fas fa-plus"></i> Ajouter</a></h3>
        </div> -->
        <!-- /.card-header -->
        <div class="card-body">
    <table id="tableName" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Numéro</th>
                <th>Besoin</th>
                <th>Motif</th>
                <th>Demandeur</th>
                <th>@Html.DisplayNameFor(model => model.DirectionLibelle)</th>
                <th>@Html.DisplayNameFor(model => model.DepartementLibelle)</th>
                <th>Statut</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
           </thead>
                 
        </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</div>


@section Scripts{
    <!-- Page specific script -->
    <script>
        $(function () {
           var table = $("#tableName").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                processing: true,
                serverSide: true,
                filter: true,
                ajax: {
                    url: "@Url.Action("GetExpressionBesoinsListValider", "ExpressionBesoins")",
                    type: "POST",
                },
                columns: [
                    { data: "Id", name: "Id" },
                    { data: "NumExpressionBesoin", name: "NumExpressionBesoin" },
                    { data: "NatureBesoin", name: "NatureBesoin" },
                    { data: "MotifDemande", name: "MotifDemande" },
                    { data: "NomDemandeur", name: "NomDemandeur" },
                    { data: "DirectionLibelle", name: "DirectionLibelle" },
                    { data: "DepartementLibelle", name: "DepartementLibelle" },
                    {
                        data: "DernierStatut", render: function (data, type, row, meta) {
                            if (data == 'VALIDER') {
                                return type === 'display' ?'<span class="badge badge-success" >' + data + '</span>' : data;
                            } if (data == 'REJETER') {
                                return type === 'display' ? '<span class="badge badge-danger" >' + data + '</span>' : data;
                            }
                            else{
                                return type === 'display' ? '<span class="badge badge-info" >' + data + '</span>' : data;
                            }
                            
                        }
                    },
                    { data: "DateDemande", name: "DateDemande" },
                    {
                        data: "Id", render: function (data, type, row, meta) {
                            var action = '<div>';
                            if (type === 'display') {
                                action += '<a href="/ItemsExpressionBesoins/List/' + data + '" ><i class="fas fa-plus"></i></a> ';
                                if (row.DernierStatut == "CREER") {
                                    action += ' <a id="editButton" data-eb=' + data + ' href="#" ><i class="fas fa-edit"></i></a> ';
                                }
                                
                            }
                            action += '</div>';
                            return action;
                        }
                    }
                ]
            });



            $("#addButton").click(function () {
                //var customerId = $(this).closest("tr").find("td").eq(0).html();
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Create", "ExpressionBesoins")",
                    //data: { "customerId": customerId },
                    success: function (response) {
                        $("#partialModal").find(".modal-content").html(response);
                        $("#partialModal").modal('show');
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            });


            $(document).on('click', '#SaveData', function (e) {
                e.preventDefault();
                var form = $(this).parents('form:first');
                var formData = form.serialize();
                $.ajax(
                    {
                        type: 'post',
                        url: "@Url.Action("Create", "ExpressionBesoins")",
                        data: formData,
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (result) {
                            //table.draw();
                            table.ajax.reload();
                            $('#partialModal').modal('hide');
                            var url = '@Url.Action("List", "ItemsExpressionBesoins")/'+ result;
                            console.log(url);
                            window.location.href = url;
                        }
                    });
            });



            //Edit script
            //Modifier une expression besion editButton
            $(document).on('click', '#editButton', function (e) {
                e.preventDefault();
                var id = $(this).data('eb');
                var url = "@Url.Action("ModifierExpressionBesoin", "ExpressionBesoins")/" + id;
                console.log('TEST OK'+id);
                //var customerId = $(this).closest("tr").find("td").eq(0).html();
                $.ajax({
                    type: "GET",
                    url: url,
                    //data: { "customerId": customerId },
                    success: function (response) {
                        $("#partialModal").find(".modal-content").html(response);
                        $("#partialModal").modal('show');
                        $('.modal-dialog').css('max-width', '50%');
                        //$('#myFormSoumettre input').prop('readonly', true);
                        //$('#myFormSoumettre textarea').prop('readonly', true);
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            });

            $(document).on('click', '#ModifierData', function (e) {
                e.preventDefault();
                var id = $(this).data('eb');
                var url = "@Url.Action("ModifierExpressionBesoin", "ExpressionBesoins")";
                console.log('TEST OK' + url);
                var form = $(this).parents('form:first');
                var formData = form.serialize();
                $.ajax(
                    {
                        type: 'post',
                        url: url,
                        data: formData,
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (result) {
                            //table.draw();
                            console.log(result);
                            table.ajax.reload();
                            $('#partialModal').modal('hide');
                        }
                    });
            });

            //Detail script

            //Delete script

              
        });
    </script>

}