GestionAchatErp/Models/Signature.cs
namespace GestionAchatErp.Models
{
    public class Signature
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public int DirectionId { get; set; }
        public int DepartementId { get; set; }
        public string SignaturePath { get; set;}
        public string AuteurSignature { get; set; }
        public string DirectionLibelle { get; set; }
        public string DepartementLibelle { get; set; }

        public DateTimeOffset DateSignature { get; set; }
        public virtual UserProfile UserProfile { get; set; }

    }
}

GestionAchatErp/Controllers/Api/SignatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionAchatErp.Data;
using GestionAchatErp.Models;
using GestionAchatErp.Models.SyncfusionViewModels;

namespace GestionAchatErp.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/Signature")]
    public class SignaturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SignaturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Signature
        [HttpGet]
        public async Task<IActionResult> GetSignatures()
        {
            List<Signature> Signature = await _context.Signature.ToListAsync();
            int Count = Signature.Count();
            return Ok(new { Signature, Count });
        }


        [HttpPost("[action]")]
        public IActionResult Insert([FromBody] CrudViewModel<Signature> payload)
        {
            Signature Signature = payload.value;
            _context.Signature.Add(Signature);
            _context.SaveChanges();
            return Ok(Signature);
        }

        [HttpPost("[action]")]
        public IActionResult Update([FromBody] CrudViewModel<Signature> payload)
        {
            Signature Signature = payload.value;
            _context.Signature.Update(Signature);
            _context.SaveChanges();
            return Ok(Signature);
        }

        [HttpPost("[action]")]
        public IActionResult Remove([FromBody] CrudViewModel<Signature> payload)
        {
            Signature Signature = _context.Signature
                 .Where(x => x.Id == (int)payload.key)
                 .FirstOrDefault();
            _context.Signature.Remove(Signature);
            _context.SaveChanges();
            return Ok(Signature);

        }


    }
}

GestionAchatErp/Controllers/SignaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionAchatErp.Data;
using GestionAchatErp.Models;
using Microsoft.AspNetCore.Identity;
using static GestionAchatErp.Pages.MainMenu;
using GestionAchatErp.Services;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using GestionAchatErp.Models.SyncfusionViewModels;
using GestionAchatErp.Models.Request;

namespace GestionAchatErp.Controllers
{
    public class SignaturesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IFunctional _functionalService;
        private readonly IHostingEnvironment _env;


        public SignaturesController(IFunctional functionalService,
            IHostingEnvironment env,
            ApplicationDbContext context, 
                UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _functionalService = functionalService;
            _env = env;
        }
         
        // GET: Signatures
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Signature.Include(e => e.UserProfile);
            return View(await applicationDbContext.ToListAsync());
        }

        [HttpPost]
        public JsonResult GetSignaturesList()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var data = _context.Set<Signature>().AsQueryable();
            //get total count of data in table
            totalRecord = data.Count();
            // search data when search value found
            if (!string.IsNullOrEmpty(searchValue))
            {
                data = data.Where(x => x.AuteurSignature.ToLower().Contains(searchValue.ToLower()) || x.DirectionId.Equals(searchValue.ToLower()) || x.DepartementId.Equals(searchValue.ToLower()));
            }
            // get total count of records after search
            filterRecord = data.Count();
            //sort data
            //if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection)) data = data.OrderBy(sortColumn + " " + sortColumnDirection);
            //pagination
            var empList = data.Skip(skip).Take(pageSize).ToList();
            var returnObj = new
            {
                draw = draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = empList
            };

            return Json(returnObj);
        }

        // GET: Signatures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Signature == null)
            {
                return NotFound();
            }

            var signature = await _context.Signature
                .Include(s => s.UserProfile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (signature == null)
            {
                return NotFound();
            }

            return View(signature);
        }

        // GET: Signatures/Create
        public IActionResult Create()
        {
            ViewData["UserProfile"] = new SelectList(_context.UserProfile, "UserProfileId", "FirstName");
            return PartialView("Create");
        }

        // POST: Signatures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestSizeLimit(5000000)]
        public async Task<IActionResult> Create(SignatureRequest signature)
        {
            if (ModelState.IsValid)
            {
                var files = new List<IFormFile>();
                files.Add(signature.SignaturePath);
                var model = new Signature();

                ApplicationUser user = await _userManager.GetUserAsync(User);
                UserProfile userProfile = _context.UserProfile.SingleOrDefault(x => x.ApplicationUserId.Equals(user.Id));
                var folderUpload = "upload-signatures";
                var fileName = await _functionalService.UploadFile(files, _env, folderUpload);
              
                if (userProfile != null)
                {
                    var direction = _context.Direction.FirstOrDefault(x => x.Id == userProfile.DirectionId);
                    var departement = _context.Departement.FirstOrDefault(x => x.Id == userProfile.DepartementId);

                    model.UserProfileId = userProfile.UserProfileId;
                    model.UserProfile = userProfile;
                    model.DirectionId = userProfile.DirectionId;
                    model.DirectionLibelle = direction.Libelle;
                    model.DepartementLibelle= departement.Libelle;
                    model.DepartementId = userProfile.DepartementId;
                    model.SignaturePath = "/" + folderUpload + "/" + fileName;

                }
                model.AuteurSignature = signature.AuteurSignature;
                model.DateSignature = DateTime.Now;
                _context.Add(model);
                await _context.SaveChangesAsync();
                return Content("OK");
            }
            return Content("NOK");
        }

        // GET: Signatures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Signature == null)
            {
                return NotFound();
            }

            var signature = await _context.Signature.FindAsync(id);
            if (signature == null)
            {
                return NotFound();
            }
            ViewData["UserProfileId"] = new SelectList(_context.UserProfile, "UserProfileId", "UserProfileId", signature.UserProfileId);
            return View(signature);
        }

        // POST: Signatures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserProfileId,DirectionId,DepartementId,SignaturePath,AuteurSignature,DateSignature")] Signature signature)
        {
            if (id != signature.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(signature);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SignatureExists(signature.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserProfileId"] = new SelectList(_context.UserProfile, "UserProfileId", "UserProfileId", signature.UserProfileId);
            return View(signature);
        }

        // GET: Signatures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Signature == null)
            {
                return NotFound();
            }

            var signature = await _context.Signature.FindAsync(id);

            if (signature == null)
            {
                return NotFound();
            }

            if (signature != null)
            {
                _context.Signature.Remove(signature);
                await _context.SaveChangesAsync();
                return Content("OK");
            }
            else
            {
                return Content("NOK");
            }

            
        }

        // POST: Signatures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Signature == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Signature'  is null.");
            }
            var signature = await _context.Signature.FindAsync(id);
            if (signature != null)
            {
                _context.Signature.Remove(signature);
            }
            
            await _context.SaveChangesAsync();
            return Content("OK");
        }

        private bool SignatureExists(int id)
        {
          return _context.Signature.Any(e => e.Id == id);
        }
    }
}

GestionAchatErp/Views/Signatures/Create.cshtml
@model GestionAchatErp.Models.Signature



<div class="modal-header">
    <h4 class="modal-title">Ajout: Signature</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>


<div class="modal-body">
    <form id="myForm" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="SignaturePath" class="control-label"></label>
                    <input asp-for="SignaturePath" type="file" class="form-control"/>
                    <span asp-validation-for="SignaturePath" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="AuteurSignature" class="control-label"></label>
                    <select asp-for="AuteurSignature" class="form-control" asp-items="ViewBag.UserProfile"></select>
                    <span asp-validation-for="AuteurSignature" class="text-danger"></span>
                </div>
            </div>
          
        </div>

        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            <button type="button" id="SaveData" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
</div>

GestionAchatErp/Views/Signatures/Delete.cshtml
@model GestionAchatErp.Models.Signature

<div class="modal-header">
    <h4 class="modal-title">Ajout: Signature</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>

<div class="modal-body">
    <h3>Are you sure you want to delete this?</h3> 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DirectionId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DirectionId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartementId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartementId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SignaturePath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SignaturePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuteurSignature)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuteurSignature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateSignature)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateSignature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserProfile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserProfile.UserProfileId)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GestionAchatErp/Views/Signatures/Details.cshtml
@model GestionAchatErp.Models.Signature

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Signature</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DirectionId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DirectionId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartementId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartementId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SignaturePath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SignaturePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuteurSignature)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuteurSignature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateSignature)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateSignature)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserProfile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserProfile.UserProfileId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

GestionAchatErp/Views/Signatures/Edit.cshtml
@model GestionAchatErp.Models.Signature

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Signature</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserProfileId" class="control-label"></label>
                <select asp-for="UserProfileId" class="form-control" asp-items="ViewBag.UserProfileId"></select>
                <span asp-validation-for="UserProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DirectionId" class="control-label"></label>
                <input asp-for="DirectionId" class="form-control" />
                <span asp-validation-for="DirectionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartementId" class="control-label"></label>
                <input asp-for="DepartementId" class="form-control" />
                <span asp-validation-for="DepartementId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SignaturePath" class="control-label"></label>
                <input asp-for="SignaturePath" class="form-control" />
                <span asp-validation-for="SignaturePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuteurSignature" class="control-label"></label>
                <input asp-for="AuteurSignature" class="form-control" />
                <span asp-validation-for="AuteurSignature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateSignature" class="control-label"></label>
                <input asp-for="DateSignature" class="form-control" />
                <span asp-validation-for="DateSignature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

GestionAchatErp/Views/Signatures/Index.cshtml
@model IEnumerable<GestionAchatErp.Models.Signature>
<div class="container-fluid">


    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <h3 class="card-title"> <a class="btn btn-primary" id="addButton"> <i class="fas fa-plus"></i> Ajouter</a></h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="tableSignature" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>##</th>
                        <th>Signature </th>
                        <th>Auteur</th>
                        <th>@Html.DisplayNameFor(model => model.DirectionLibelle)</th>
                        <th>@Html.DisplayNameFor(model => model.DepartementLibelle)</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>

            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</div>
@section Styles{
    <link rel='stylesheet' href='~/sweetalert/sweetalert2.min.css'></link>

}

@section Scripts{
    <!-- Page specific script -->
    <script src="~/sweetalert/sweetalert2.all.min.js"></script>
    <script>
        
        $(function () {
            var table = $("#tableSignature").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                processing: true,
                serverSide: true,
                filter: true,
                ajax: {
                    // url: "ExpressionBesoins/GetExpressionBesoinsList",
                    url: "@Url.Action("GetSignaturesList", "Signatures")",
                    type: "POST",
                },
                columns: [
                    { data: "Id", name: "Id" },
                    {
                        data: "SignaturePath", render: function(data, type, row, meta){
                            return '<img id="profilePicture" class="profile-user-img img-responsive img-circle" src = "'+data+'" alt = "Signature" >';

                        } 
                    },
                    { data: "AuteurSignature", name: "AuteurSignature" },
                    { data: "DirectionLibelle", name: "DirectionLibelle" },
                    { data: "DepartementLibelle", name: "DepartementLibelle" },
                    { data: "DateSignature", name: "DateSignature" },
                    {
                        data: "Id", render: function (data, type, row, meta) {
                            var action = '<a href="#" ><i class="fas fa-edit"></i></a> <a id="deleteButton" href="#" data-href="/Signatures/Delete/'+data+'"><i  class="fas fa-trash"></i></a>'
                                ;
                            return action;
                        }
                    }
                ]
            });


            $('#tableSignature').on('click', '#deleteButton', function () {
                var href = this.dataset.href;
                swal({
                    title: 'Voulez-vous vraiment supprimer la signature ?',
                    showCancelButton: true,
                    showConfirmButton: true,
                    confirmButtonText: 'Oui, Je supprime',
                    cancelButtonText: 'Non, Annuler',
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger',
                    type: 'warning',
                    buttonsStyling: true
                }).then((result) => {
                    console.log(result);
                    if (result.value) {
                        console.log(href);
                            $.ajax({
                                type: "GET",
                                url: href,
                                success: function (response) {
                                    console.log(response);
                                    table.ajax.reload();
                                swal('Supprimé', '', 'success');
                                },
                                failure: function (response) {
                                    console.log(response.responseText);
                                },
                                error: function (response) {
                                    console.log(response.responseText);
                                }
                            });
                        }
                        else{
                            swal('Annulé', '', 'error');
                        }
                    });


               /* */
            });

            

            $("#addButton").click(function () {
                //var customerId = $(this).closest("tr").find("td").eq(0).html();
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Create", "Signatures")",
                    //data: { "customerId": customerId },
                    success: function (response) {
                        $("#partialModal").find(".modal-content").html(response);
                        $("#partialModal").modal('show');
                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            });


            $(document).on('click', '#SaveData', function (e) {
                e.preventDefault();
                var form = $(this).parents('form:first');
                //console.log(form);
                 var formData = new FormData(form[0]);

                //var SignaturePath = form.SignaturePath;

                //console.log(SignaturePath);
                //var formData = form.serialize();
                //formData['SignaturePath'] = SignaturePath;

                $.ajax(
                    {
                        type: 'post',
                        url: "@Url.Action("Create", "Signatures")",
                        data: formData,
                        contentType: false,
                        processData: false,
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (result) {
                            //table.draw();
                            table.ajax.reload();
                            $('#partialModal').modal('hide');
                        }
                    });
            });



            //Edit script

            //Detail script

            //Delete script


        });
    </script>

}